### ISSUE TITLE
Dead or Alive 3 USA widescreen incorrect display

### ISSUE THREAD

**Issue by kimbapslice** [MakeMHz/xbox-hd-plus#14]
DOA 3 USA version widescreen is displaying with cropped or shifted to the right. PAL version works correctly. USA is an older software revision so I think the way the actual game handles image output differs.

![PXL_20210307_200816515 MP](https://user-images.githubusercontent.com/58018661/110253322-b924a180-7f57-11eb-8823-85a4fe9f8976.jpg)

Tested on:
Imaged is cropped on the right side
Xbox 1.4 (ntsc)
XboxHDMI firmware 1.2.1
Kernel Patch 1.3.1 (evox m8plus)
Xbox HDMI software 1.0.3 - all settings are default
Widescreen, 480p disabled, 720p and 1080i enabled
LG tv aspect ratio set to auto/"determined by program"
Aspect ratio reported is 4:3 480p

Compared against:
**Aspect ratio flag seems to be 4:3.**
Xbox 1.0/1.1 stock (ntsc)
Official MS HD Pack
MS stock dashboard (latest)
Widescreen
480p enabled, 720p and 1080i enabled
Widescreen image displays correct when tv set to 16:9, squished when set to auto. 
Image is not cropped

**Comment by LoveMHz** [comment]
@kimbapslice thank you so much for the detailed issue report. I just wanted to add a note that this issue hasn't been overlooked, we've just been swamped, and I will take a look ASAP.

**Comment by uberpolka** [comment]
I don't believe this is XboxHDMI specific. I have seen the same behavior on non-hdmi consoles.
I thought it was an issue with my OSSC settings at first. 

480p enabled in the dashboard works correctly.
480p disabled in dashboard with 480p patched bios exhibits the issue.

Again, this was seen before XboxHDMI was released.

**Comment by dzastsed** [comment]
I noticed the same issue happening, if you have 480p disabled in dashboard, both eith xboxhdmi modded console and with one, which has force 480p bios and uses component cables

**Comment by LoveMHz** [comment]
@uberpolka @dzastsed thanks for the confirmations. In that case, it should be a simple workaround in v2 of the firmware/patch. We're handling mode detection at the kernel level for per-game control since this isn't the only odd case of 480p disabled/720p enabled causing unexpected behavior. Conker: Live and Reloaded, Max Payne (Crash), and Monopoly (Crash) just to name a few.

I'm going to leave this open until the patch is released and tested.

**Comment by kimbapslice** [comment]
Working correctly as of 2.1.5. Thanks for fixing this Dustin!
