### ISSUE TITLE
Conker: Live & Reloaded Overscan Issue

### ISSUE THREAD

**Issue by TheLegendOfXela** [MakeMHz/xbox-hd-plus#19]
When 480p is turned off, and 480p is forced by the edited bios, Conker still has overscan bars.

**Comment by TheLegendOfXela** [comment]
I’m a buffoon

**Comment by dracc** [comment]
> I’m a buffoon

How so? @TheLegendOfXela

**Comment by TheLegendOfXela** [comment]
> > I’m a buffoon
> 
> How so? @TheLegendOfXela

According to 2 other users on the discord, Conker works without overscan bars.
