### ISSUE TITLE
1.6 xbox with 1.3.2 patch shows 55hz refresh choppy video output

### ISSUE THREAD

**Issue by kimbapslice** [MakeMHz/xbox-hd-plus#20]
Setup:
Xbox 1.6, xboxhdmi, otherwise stock
Firmware 1.2.2
Kernel Patch 1.3.2 built from m8plus (M8_16_LBA48_IGR_Q-06.bin) | 0c7ff9e58c7ae9ee5225944ce01daae1
MS Dashboard options 480p off, 720p on, 1080i on, digital audio all enabled

When hooked up to my TCL 4k 43s515, the opening bios screen and in game (Panzer Dragoon Orta USA) stutters and shows 55hz refresh. 
Running stock bios and "stock" evox8plus 1.6 video does not glitch. When hooked up to my ancient LG 1080p 55LV9500-UA, patched bios appears better but the motion of the graphics doesn't seem as smooth (ie not 60hz).

1.4 xboxhdmi, firmware 1.2.1, running evox8+ lba48 igr q 06 patch 1.3.2 on the TCL 4K shows 60hz and bios opening and in game seems to be running normally.

**Comment by Runwave87** [comment]
Setup:
XBOX 1.6, xboxhdmi 1.4 with firmware 1.2.2, openxenium, hdd with sata adapter. Kernel patch 1.3.2. Widescreen, 480p off, 720p on, 1080i off.
Samsung ln46b500p3fxza. 
Stock m8+ bios will show xbox splash boot screen, dashboard at 720p good no audio glitches.
Patched bios will not show xbox splash boot screen, black screen until dashboard showing mode not supported.  Dashboard works fine at 720p , most games give black screen unless 720p title. Openxenium display works fine.

Same tv has zero issues with 1.0 system with xboxhdmi firmware 1.0.0 and patch 1.3.1.

1.6 system with sharp lc-40le830u will show xbox splash screen at 56hz, but at dash audio will cut out with tv saying unsupported audio. Halo will boot but audio cuts out. System acts normal with stock m8+ bios.

1.0 system system works fine with this TV with 1.3.1 patched bios

**Comment by LoveMHz** [comment]
Resolved in FW2.1.x
