### ISSUE TITLE
Cannot force 4:3 on widescreen-compatible games (XboxHD+)

### ISSUE THREAD

**Issue by bahamutfan64** [MakeMHz/xbox-hd-plus#25]
The XboxHD+ app settings do not allow for games which support widescreen to be forced to run in the 4:3 aspect ratio.

For some games like Halo 2 there is a mismatch between the viewport and the stretched out HUD elements.  Many titles also utilize anamorphic widescreen (or rather, they stretch out 720x480p, instead of actually utilizing 858x480p) leading to a less sharp image. 

For that reason, could I please request that a forced 4:3 be added so that games can no longer engage their widescreen mode?

**Comment by Kobeskillz** [comment]
I am also having this issue as well.

**Comment by LoveMHz** [comment]
Resolved in FW2.1.x
