### ISSUE TITLE
no picture after installation

### ISSUE THREAD

**Issue by peewee82** [MakeMHz/xbox-hd-plus#27]
I have the following problem, after the installation a blue led flashes and no picture appears.
When I pull out the hdmi cable and plug it in again, a picture appears and a green LED lights up continuously, but the blue one continues to flash.
I am sure that I didn’t make any mistakes during the installation and have checked it several times.
What does the blinking of the blue led mean?
I also miss a biospatch for BIOS, which support f and g partitions.

I used latest patches for XBOXHD+ on a 1.4 XBOX witch ALADDIN chip and standard M8Plus BIOS (checksum fits).

In your tutorial you wrote, I have to solder to 1V8 point. But were is it, at revision 5b of the board???

**Comment by Redherring32** [comment]
XboxHD+ doesn't need the 1V8 wire, I assume you're reading the XboxHDMI guide, as for the blue LED blinking, that's normal behavior. 

It also sounds like your cable is misbehaving, I would recommend trying another, some cables are a but iffy.

**Comment by peewee82** [comment]
Thanks for your fast reply. No, i looked in the correct tutorial. Maybe its wrong written in it? You can find that information on picture and written down in the tut itself.
I tried 3 different TV (Sony, Panasonic, Medion) and 3 different cables. The effect is the same. All three cables are Higspeed 2.1 HDMI Cables. I dont know, what i can try more...

**Comment by LoveMHz** [comment]
This repo is not for installation troubleshooting. Please join our Discord server where we can assist you in real-time.
https://discord.gg/9YcuDpY
