### ISSUE TITLE
Bios choice 

### ISSUE THREAD

**Issue by Arp59310** [MakeMHz/xbox-hd-plus#28]
Hello,

i have an aladdin xt plus2 and i don’t know what bios i have to choose at step 3. 

Thx

**Comment by dracc** [comment]
You want the same modified m8plus as anyone else. How you flash it onto your chip is a different story. I'm sure you can find dozens of great guides for your chip if you search the web. The search term "Flash BIOS on Aladdin XT" ought to yield results.

**Comment by LoveMHz** [comment]
This repo is not for installation troubleshooting. Please join our Discord server where we can assist you in real-time.
https://discord.gg/9YcuDpY
