### ISSUE TITLE
Original XBOX HDMI board for 1.6 xbox

### ISSUE THREAD

**Issue by Waterrat26** [MakeMHz/xbox-hd-plus#29]
Hi I've finally installed this board, all went well, it boots and the xbox loading screen comes on with no audio or visual issues. But once it goes onto the XBMC page i here static??? So I resoldered the cables, just to check connecttions but no luck.

**Comment by LoveMHz** [comment]
This repo is not for installation troubleshooting. Please join our Discord server where we can assist you in real-time.

https://discord.gg/9YcuDpY
