### ISSUE TITLE
Console 5 Capacitor fitment issue for V1.0 revision

### ISSUE THREAD

**Issue by crispycritter911** [MakeMHz/xbox-hd-plus#30]
I've recapped the mother board and power supply of a v1.0 motherboard. The capacitor located at C5A3 is a 10v 680uF capacitor. It interferes with the HD+ motherboard. I had to shave the HD+ board down carefully with a file and bend the capacitor legs to fit. I'd suggest checking fitment of the capacitor and possibly leave the legs a little bit longer to clear the board or find a different capacitor to replace it. I'll email the person at console5 and inform him too.

**Comment by LoveMHz** [comment]
Can you share a picture? I've used the kits before and haven't run into any issues.

**Comment by crispycritter911** [comment]
I've reached out to Luke from Console5,  he plans on revising the capacitor in his kits and send me a replacement one.
![20220107_101806](https://user-images.githubusercontent.com/11153854/148577246-a252f707-09e1-481e-937b-18ed1fb32d82.jpg)
![20220107_102046](https://user-images.githubusercontent.com/11153854/148577248-29d367f6-8407-42c1-9d06-2996d049228c.jpg)
![20220107_101802](https://user-images.githubusercontent.com/11153854/148577252-bed0646c-77e0-49e7-8def-cad0d1dd0983.jpg)

**Comment by crispycritter911** [comment]
![20220119_181652](https://user-images.githubusercontent.com/11153854/150246136-6a9b4040-eba3-4971-8570-2d9b60febe4d.jpg)
![20220119_181737](https://user-images.githubusercontent.com/11153854/150246139-90d6d0c2-2cd0-40eb-aaa1-6057db95e77f.jpg)
![20220119_181746](https://user-images.githubusercontent.com/11153854/150246142-f4f6df20-ed2b-4ad8-a16a-a78210ab6c58.jpg)
![20220119_182629](https://user-images.githubusercontent.com/11153854/150246144-e4242f5c-2274-4b6b-84c9-c47dd00e5a91.jpg)

**Comment by crispycritter911** [comment]
Check the capacitor voltage. The original one sent was 16 volts at 10mm diameter where as the smaller one was 10 volts and only 8mm in diameter
