### ISSUE TITLE
Issues and new BIOS MD5

### ISSUE THREAD

**Issue by L10N37** [MakeMHz/xbox-hd-plus#31]
Hi guys, just a few things here :)

Guide has not being updated in regards to the 1v8 point, this isn't on the HDMI PCB ...it's skipped on the installation, but it's on the guide.

Guide still says to install legacy patch, but there's the new XBOXHD+ kernel patch at the top of the patches page.

XBMC is showing a CPU temp of 1075 degrees, it doesn't do this unless the XBOXHD+ FW folder is installed and the FW is active. It was showing the system idling at ~49 degrees prior.

The XBOX HD+ app crashes upon exit, no matter where it's launched from (on both the BIOS's im about to mention)

This isn't really *your issue* but i feel it should be mentioned: The M8 Plus BIOS (MD5: dfc6288f6b67fd021e1970491c64c0a0) listed doesn't support LBA48, so large hard drives are out of the question.  I found one with LBA48 V3 in the TruHexen2020 engineering discs BIOS folder, it's MD5 is   < 94acfb5b4ddd81515386e733ea0020f3 >

Finally, the kernel patch seems to kill the ability to launch the rocky5 extras disc at launch (my preferred way of XBMC installation, as it's hassle free and super simple).  I can still launch it once a dash is launched, but it will not launch at boot anymore for some reason.

**Comment by L10N37** [comment]
https://imgur.com/gallery/BA2mfll

here's the temp 
and a tiny bit of area on the top, the entire image needs to be shifted up a little

**Comment by dzastsed** [comment]
https://github.com/MakeMHz/xbox-hd-plus/issues/24

**Comment by L10N37** [comment]
I'm not too concerned about the temp.
the image wasn't shifted down with the original BIOS that I used but that didn't have the LBA48 so I had to switch out. Any chance of a fix for the BIOS mentioned above (shared the hash) so that the image is moved up a little ?? or a feature in the app to allow manual shifting on the X and Y axis ?

**Comment by dzastsed** [comment]
shifted down image issue is known as well, and will be fixed in next bios update according to dustin (a side effect of upscaling or something like that). if you don't like it you can disable upscaling by setting video out to 480p in xboxhd+ settings

**Comment by L10N37** [comment]
yeah I thought this may have happened after I locked 720P.
no worries. Thanks for the heads up :)

**Comment by catogtp** [comment]
"_This isn't really your issue but i feel it should be mentioned: The M8 Plus BIOS (MD5: dfc6288f6b67fd021e1970491c64c0a0) listed doesn't support LBA48, so large hard drives are out of the question._ "

If you open any vanilla M8 in evtool and then save it as a new bios.bin file, the v3 LBA48 patch is added automatically.
