### ISSUE TITLE
Stereo only!!! Dolby Digital broken. Not working most of the time.

### ISSUE THREAD

**Issue by Kobeskillz** [MakeMHz/xbox-hd-plus#32]
Hey guys this is driving me absolutely insane. The audio only comes out in stereo no matter what i do. I've tested every single thing for hours and i might get Dolby Digital 1 out of 10-15 tries. I changed wires and tested everything. My Receiver is a denon so it can handle simple dolby which i got before the mod with optical. Please help.

**Comment by carlocgc** [comment]
Duplicate of #26

**Comment by Kobeskillz** [comment]
Yeah it's a duplicated but i was told to post it here. Just wanna make sure it doesn't get missed it's such a nightmare dealing with this issue.

**Comment by LoveMHz** [comment]
Duplicate of #26
