### ISSUE TITLE
1.6 xbox no kernel patch

### ISSUE THREAD

**Issue by Randalthor81** [MakeMHz/xbox-hd-plus#33]
I followed the guide exactly. When I checked for the kernel patch it was there. Now that I've done the hd+ mod I just get a blank screen unless I boot hexen from a disk. Now it says I don't have the kernel patch. I have no idea how to boot back into open xenium to reapply the patch.

**Comment by Randalthor81** [comment]
Idk if I was clear. Essentially it still boots, I just cannot get into the open xenium os screen. But the system still reads disks and loads to the dashboard. The hdmi is working.

**Comment by LoveMHz** [comment]
Our Discord server is the best place to ask these types of questions where our community members can help you in real-time.
https://discord.gg/9YcuDpY

This issue will be closed as it doesn't address a specific issue. (Though one could be opened for adding troubleshooting steps).

**Comment by Randalthor81** [comment]
Just joined but it won't allow me to type anything. Sorry new to discord
