### ISSUE TITLE
Link to bios patchs not working

### ISSUE THREAD

**Issue by Quickplay-nl** [MakeMHz/xbox-hd-plus#34]
Hi i'm installing the hd+ but i'm stuck at software part the link to bios patches is not working please check this and update so i can continue the install.

**Comment by catogtp** [comment]
Working for me: https://github.com/MakeMHz/xbox-hd-plus/blob/master/patches/README.md#xbox-kernel-patches-kpatch---xboxhd

**Comment by Quickplay-nl** [comment]
here now also working thnx for quick response dont know what was wrong but now working
