### ISSUE TITLE
Can't access HDD

### ISSUE THREAD

**Issue by dahlers1988** [MakeMHz/xbox-hd-plus#35]
I followed the instructions up until transfering over the app to the hhd. When I FTP, all I see is the root (/) with nothing in it. No C:, D:, etc.. It shows it's connected. Side note: I can FTP fine with UnleashX but not EvoX.

**Comment by dracc** [comment]
So, EvolutionX FTP is broken for you?

**Comment by dahlers1988** [comment]
Yes, but UnleashX works fine.. weird. I've been round and round with it for days. Is there a way around this? Like, FTP with UnleashX, then boot with the OpenXenium modchip?

**Comment by dracc** [comment]
> Yes, but UnleashX works fine.. weird. I've been round and round with it for days. Is there a way around this? Like, FTP with UnleashX, then boot with the OpenXenium modchip?

When/Why are you booting *without* the OpenXenium modchip?
I'm sorry, but I'm having a hard time following your lead.

**Comment by catogtp** [comment]
Disable the list hidden files command in your ftp client. The FTP implementation in OX does not like that and returns emptyu results.

**Comment by catogtp** [comment]
Here is an example of the command setting in the FTP client I use, FlashFXP
![FTP_List_Hidden](https://user-images.githubusercontent.com/29710948/157440263-8808138b-4524-46d7-ac47-63114507c849.png)

**Comment by catogtp** [comment]
> @catogtp thank you! I think it fixed it. Now, I'm having an unrelated EvoX issue. Won't load default xbe. I think i can figure that out on my own. Thanks again!!

@dahlers1988 we're on discord if you need further assistance, typically the issues section here is for items directly related to the HD+. We can help you through other issues/setups via discord, feel free to come check it out.
