### ISSUE TITLE
Adding Beta XOR'ing keys to the kernel

### ISSUE THREAD

**Issue by MRiCEQB** [MakeMHz/xbox-hd-plus#37]
Don't know if it's possible, but here goes.

Xbox Live Beta Test builds of Lamborghini and Re-Volt are now released.

The people who analyzed the executables figured out, that Microsoft used a previously unknown key to XOR the kernel and entrypoint addresses.
It has been documented here today:

https://xboxdevwiki.net/index.php?title=Xbe&curid=3706&diff=7038&oldid=6968

Now the question is, if it's possible to include this key in in the patches fornthe kernel, so it's able to decrypt the addresses on it's own, without modifying the game files.

**Comment by LoveMHz** [comment]
Closing this as it's outside the scope of this project.

Sounds like it might be best to patch this software manually.
