### ISSUE TITLE
New Project Stellar and XBOX HD+ v2 install

### ISSUE THREAD

**Issue by ejlg87** [MakeMHz/xbox-hd-plus#44]
Greetings, hoping to get some guidance. Please see attached photos. I can’t seem to fix this issue and I’m not sure if it’s software related or just bad luck. XBOX 1.0
![IMG_0870](https://user-images.githubusercontent.com/131617375/233861760-50005eca-d735-4a61-badb-21c6db78aa35.jpeg)

**Comment by LoveMHz** [comment]
This repo is not for installation troubleshooting. Please join our Discord server where we can assist you in real-time.
https://discord.gg/9YcuDpY
